# Generated by Django 5.2.7 on 2026-04-09 04:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('scene', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('emotional', 'Emotional Analysis'), ('visual', 'Visual Analysis'), ('audio', 'Audio Analysis'), ('pacing', 'Pacing Analysis'), ('narrative', 'Narrative Analysis'), ('cinematography', 'Cinematography Analysis'), ('other', 'Other')], max_length=50)),
                ('score', models.FloatField(help_text='Analysis score from 0-10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('confidence', models.FloatField(help_text='Confidence level of the analysis (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('summary', models.TextField()),
                ('detailed_findings', models.JSONField(blank=True, default=dict)),
                ('analyzed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('methodology', models.CharField(blank=True, max_length=255, null=True)),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='scene.scene')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('threshold_min', models.FloatField(blank=True, null=True)),
                ('threshold_max', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analysis.sceneanalysis')),
            ],
            options={
                'ordering': ['metric_name'],
            },
        ),
        migrations.CreateModel(
            name='MovieAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('structure', 'Story Structure'), ('themes', 'Themes'), ('character', 'Character Analysis'), ('production', 'Production Quality'), ('audience', 'Audience Reception'), ('critical', 'Critical Analysis'), ('other', 'Other')], max_length=50)),
                ('rating', models.FloatField(help_text='Overall rating from 0-10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('analyst', models.CharField(blank=True, max_length=100, null=True)),
                ('methodology', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_analyses', to='movies.movie')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['movie', 'analysis_type'], name='analysis_mo_movie_i_e1505b_idx'), models.Index(fields=['analysis_type'], name='analysis_mo_analysi_7f15f4_idx'), models.Index(fields=['rating'], name='analysis_mo_rating_e8385a_idx')],
                'unique_together': {('movie', 'analysis_type')},
            },
        ),
        migrations.AddIndex(
            model_name='sceneanalysis',
            index=models.Index(fields=['scene', 'analysis_type'], name='analysis_sc_scene_i_b89fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='sceneanalysis',
            index=models.Index(fields=['analysis_type'], name='analysis_sc_analysi_052164_idx'),
        ),
        migrations.AddIndex(
            model_name='sceneanalysis',
            index=models.Index(fields=['score'], name='analysis_sc_score_59f8eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sceneanalysis',
            unique_together={('scene', 'analysis_type')},
        ),
        migrations.AddIndex(
            model_name='analysismetric',
            index=models.Index(fields=['scene_analysis', 'metric_name'], name='analysis_an_scene_a_924030_idx'),
        ),
    ]
