# Generated by Django 5.2.7 on 2026-04-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('producer', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('documentary', 'Documentary'), ('other', 'Other')], default='other', max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('cast', models.TextField(blank=True, help_text='Comma-separated list of main cast', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-release_date'],
                'indexes': [models.Index(fields=['title'], name='movies_movi_title_652549_idx'), models.Index(fields=['genre'], name='movies_movi_genre_f96e97_idx'), models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx')],
            },
        ),
    ]
