# Generated by Django 5.2.7 on 2026-04-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hulu_url',
            field=models.URLField(blank=True, help_text='Hulu page URL for the movie', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='netflix_url',
            field=models.URLField(blank=True, help_text='Netflix page URL for the movie', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='prime_video_url',
            field=models.URLField(blank=True, help_text='Amazon Prime Video page URL for the movie', null=True),
        ),
    ]
