# Generated by Django 5.2.7 on 2026-04-09 04:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scene_type', models.CharField(choices=[('action', 'Action'), ('dialogue', 'Dialogue'), ('montage', 'Montage'), ('transition', 'Transition'), ('exposition', 'Exposition'), ('climax', 'Climax'), ('other', 'Other')], default='other', max_length=50)),
                ('start_time_seconds', models.IntegerField(help_text='Scene start time in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('end_time_seconds', models.IntegerField(help_text='Scene end time in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_seconds', models.IntegerField(editable=False, help_text='Scene duration in seconds')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('characters', models.TextField(blank=True, help_text='Comma-separated list of characters', null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('scene_number', models.IntegerField(help_text='Sequential scene number in the movie')),
                ('emotional_intensity', models.IntegerField(default=5, help_text='Emotional intensity from 1-10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('key_moments', models.BooleanField(default=False, help_text='Whether this is a key/notable moment')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=500, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='movies.movie')),
            ],
            options={
                'ordering': ['movie', 'scene_number'],
                'indexes': [models.Index(fields=['movie', 'scene_number'], name='scene_scene_movie_i_5c9d74_idx'), models.Index(fields=['scene_type'], name='scene_scene_scene_t_a504e8_idx'), models.Index(fields=['key_moments'], name='scene_scene_key_mom_0a26c2_idx')],
                'unique_together': {('movie', 'scene_number')},
            },
        ),
    ]
